name: pp_17
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.4
  cupertino_icons: ^1.0.5
  get_it: ^7.2.0
  connectivity_plus: ^3.0.4
  shared_preferences: ^2.0.15
  carousel_slider: ^4.2.1
  hive: 2.2.3
  hive_flutter: ^1.1.0
  flutter_rating_bar: ^4.0.1
  in_app_review: ^2.0.4
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.1.5

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
